env:
    browser: true
    commonjs: true
    es2021: true
extends: eslint:recommended
parserOptions:
    ecmaVersion: 12
rules:
    indent: warn
    linebreak-style: warn
    quotes: warn
    semi: warn
    no-unused-vars: warn
    no-self-assign: off
    no-undef: off