extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended"]
parser: "@typescript-eslint/parser"
plugins: ["@typescript-eslint"]
ignorePatterns: "*.js"
root: true
parserOptions:
    ecmaVersion: 12
rules:
    indent: warn
    linebreak-style: warn
    quotes: warn
    semi: warn
    no-unused-vars: warn
    prefer-const: warn